pipeline {
    agent any
    stages {        
        stage('Harden') {
            steps {
                dir('nimbus-beacon-chain') { 
                    sh 'docker build -f Dockerfile_harden --build-arg=RELEASE=${RELEASE} -t stereum/nimbus-beacon-chain:${RELEASE} .'
                    sh "docker run --rm -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 1 --no-progress stereum/nimbus-beacon-chain:${RELEASE}"
                }
            }
        }
        stage('Push Hardened') {
            steps {
                dir('nimbus-beacon-chain') {                     
                    sh 'docker push stereum/nimbus-beacon-chain:${RELEASE}'
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}