pipeline {
    agent any
    stages {        
        stage('Harden') {
            steps {
                dir('nimbus-beacon-chain/hardening') { 
                    sh 'docker build -f Dockerfile --build-arg=RELEASE=${RELEASE} -t stereum/nimbus-beacon-chain:${RELEASE} .'                    
                    sh "docker run --rm -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 0 --severity CRITICAL,HIGH,LOW --no-progress stereum/nimbus-beacon-chain:${RELEASE}"
                    sh "docker run --rm -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 8 --severity CRITICAL --no-progress stereum/nimbus-beacon-chain:${RELEASE}"
                }
            }
        }
        stage('Push Hardened') {
            steps {                
                sh 'docker push stereum/nimbus-beacon-chain:${RELEASE}'                
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}