pipeline {
    agent any
    stages {        
        stage('Harden') {
            steps {
                dir('base/hardening') {
                    sh 'docker build -f Dockerfile --build-arg=BASE=${BASE} -t stereum/beacon-base:${BASE} .'                    
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 0 --severity CRITICAL,HIGH,LOW --no-progress stereum/beacon-base:${BASE}"
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 8 --severity CRITICAL --no-progress stereum/beacon-base:${BASE}"
                }
            }
        }
        stage('Push Hardened') {
            when {                
                expression { params.SKIP_PUSH == 'false' }
            }
            steps {                                
                sh 'docker push stereum/beacon-base:${BASE}'
            }
        }
    }
    post {         
        always { 
            cleanWs()
        }
    }
}
