ARG  RELEASE
FROM stereum/nimbus-beacon-chain:${RELEASE}-soft as app

FROM app as scanned
LABEL maintainer="theguys@stereum.net"
USER root
# scan image
RUN apk add --no-cache curl \
    && curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin \
    && trivy filesystem --exit-code 1 --no-progress / > /scan_result.txt 2>&1 \
    && rm /usr/local/bin/trivy \
    && rm -rf /root/.cache/trivy
# harden image
RUN rm -f /sbin/apk && rm -rf /etc/apk && rm -rf /lib/apk && rm -rf /usr/share/apk && rm -rf /var/lib/apk
USER ${SERVICE_USER}
WORKDIR ${SERVICE_HOME}
