pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                checkout scm
                dir('nimbus-beacon-chain') { 
                    sh 'docker build --build-arg=RELEASE=${RELEASE} -t stereum/nimbus-beacon-chain:${RELEASE} .'
                }
            }
        }
        stage('Push') {
            steps {
                sh 'docker push stereum/nimbus-beacon-chain:${RELEASE}'
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}