pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                checkout scm
                dir('nimbus-beacon-chain') { 
                    sh 'docker build --build-arg=RELEASE=${RELEASE} --build-arg=BEACON_BASE=${BASE} -t stereum/nimbus-beacon-chain:${RELEASE}-soft .'                    
                }
            }
        }
        stage('Push Soft') {
            steps {                                
                sh 'docker push stereum/nimbus-beacon-chain:${RELEASE}-soft'
            }
        }        
    }
    post { 
        always { 
            cleanWs()
        }
    }
}