pipeline {
    agent any
    stages {        
        stage('Harden') {
            steps {
                dir('nimbus/hardening') {                     
                    sh 'docker build -f Dockerfile --build-arg=RELEASE=${RELEASE} -t stereum/nimbus:${RELEASE} .'                                        
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 0 --severity CRITICAL,HIGH,LOW --no-progress stereum/nimbus:${RELEASE}"
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/jenkins_home/.trivy:/root/.cache/ aquasec/trivy --exit-code 8 --severity CRITICAL --no-progress stereum/nimbus:${RELEASE}"
                }
            }
        }
        stage('Push Hardened') {
            steps {                
                sh 'docker push stereum/nimbus:${RELEASE}'                
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}