ARG  BASE
FROM stereum/beacon-base:${BASE}-soft
LABEL maintainer="theguys@stereum.net"
USER root
RUN apk add --no-cache curl \
    && curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin \
    && trivy filesystem --exit-code 1 --no-progress > /scan_result.txt 2>&1 \
    && rm /usr/local/bin/trivy \
    && rm -rf /root/.cache/trivy
