pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                checkout scm
                dir('base') { 
                    sh 'docker build  --build-arg=BASE=${BASE} -t stereum/beacon-base:${BASE}-soft .'                    
                }
            }
        }
        stage('Push') {
            steps {                
                sh 'docker push stereum/beacon-base:${BASE}-soft'                
            }
        }
        stage('Hardening') {
            steps {                                                
                build job: 'beacon-base-harden', parameters: [[$class: 'StringParameterValue', name: 'BASE', value: BASE]], propagate: false, wait: false
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
