pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                checkout scm
                dir('base') { 
                    sh 'docker build  --build-arg=BASE=${BASE} -t stereum/beacon-base:${BASE} .'                    
                }
            }
        }
        stage('Push') {
            when {                
                    expression { params.SKIP_PUSH == 'false' }
            }
            steps {                
                sh 'docker push stereum/beacon-base:${BASE}'                
            }
        }        
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
